apiVersion: v1
kind: Service
metadata:
  name: {{ include "bandolier.fullname" . }}
  labels:
    {{- include "bandolier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "bandolier.selectorLabels" . | nindent 4 }}
