package main

import (
	"context"
	"errors"
	"regexp"
	"strings"
	"testing"
)

// covModeIssueJSON is the `gh issue view` payload the fake gh echoes for issue
// #42, so resolveMode's fetchIssue resolves without a real gh/GitHub.
const covModeIssueJSON = `{"number":42,"title":"Fix the flaky test","body":"It fails intermittently."}`

// covModeFakeIssueGh installs a fake `gh` on PATH that echoes covModeIssueJSON,
// letting resolveMode fetch issue #42. Reuses covGHFakeGh from the github
// coverage tests rather than duplicating the PATH-shim plumbing.
func covModeFakeIssueGh(t *testing.T) {
	t.Helper()
	covGHFakeGh(t, "#!/bin/sh\necho '"+covModeIssueJSON+"'\n")
}

// covModeRepoURL is a throwaway repo URL: resolveMode only switches on whether
// repoURL is set (it never clones), so any non-empty value selects repo mode.
const covModeRepoURL = "https://example.com/owner/repo.git"

func TestCovModePlainMode(t *testing.T) {
	t.Run("pr output: default plain run, no branch, issueOutput false", func(t *testing.T) {
		cfg := config{outputType: "pr"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != "" {
			t.Errorf("prBranch = %q, want empty in plain mode", mode.prBranch)
		}
		if mode.issueOutput {
			t.Error("issueOutput = true, want false for pr output")
		}
		if mode.issueOutput != cfg.issueOutput() {
			t.Errorf("issueOutput %v does not mirror cfg.issueOutput() %v", mode.issueOutput, cfg.issueOutput())
		}
		if cfg.systemPrompt != "" {
			t.Errorf("plain mode set a system prompt: %q", cfg.systemPrompt)
		}
	})

	t.Run("issue output: issueOutput mirrors cfg.issueOutput(), still no framing", func(t *testing.T) {
		cfg := config{outputType: "issue"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if !mode.issueOutput {
			t.Error("issueOutput = false, want true for issue output")
		}
		if mode.issueOutput != cfg.issueOutput() {
			t.Errorf("issueOutput %v does not mirror cfg.issueOutput() %v", mode.issueOutput, cfg.issueOutput())
		}
		if mode.prBranch != "" {
			t.Errorf("prBranch = %q, want empty in plain mode", mode.prBranch)
		}
		// The plain (default) switch arm builds no framing even for issue output.
		if cfg.systemPrompt != "" {
			t.Errorf("plain mode set a system prompt: %q", cfg.systemPrompt)
		}
	})
}

func TestCovModeRepoFreshPR(t *testing.T) {
	t.Run("titled fresh run cuts a slugged branch and frames the repo prompt", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, title: "Add feature", outputType: "pr"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		re := regexp.MustCompile(`^bandolier/add-feature-[0-9a-z]{6}$`)
		if !re.MatchString(mode.prBranch) {
			t.Errorf("prBranch = %q, want match %v", mode.prBranch, re)
		}
		if mode.prTitle != "Bandolier agent changes" {
			t.Errorf("prTitle = %q, want placeholder", mode.prTitle)
		}
		if mode.prBody != "Generated by Bandolier." {
			t.Errorf("prBody = %q", mode.prBody)
		}
		if mode.issueOutput {
			t.Error("issueOutput = true, want false for pr output")
		}
		if want := buildRepoSystemPrompt(mode.prBranch); cfg.systemPrompt != want {
			t.Errorf("systemPrompt = %q, want buildRepoSystemPrompt(prBranch)", cfg.systemPrompt)
		}
	})

	t.Run("empty title falls back to the task branch slug", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, title: "", outputType: "pr"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		re := regexp.MustCompile(`^bandolier/task-[0-9a-z]{6}$`)
		if !re.MatchString(mode.prBranch) {
			t.Errorf("prBranch = %q, want the task-slug fallback %v", mode.prBranch, re)
		}
	})
}

func TestCovModeRepoFreshInteractive(t *testing.T) {
	// Interactive still cuts the working branch, but leaves the system prompt
	// empty — runAgent frames the session later.
	cfg := config{repoURL: covModeRepoURL, title: "Add feature", outputType: "pr", interactive: true}
	mode, err := resolveMode(context.Background(), &cfg)
	if err != nil {
		t.Fatalf("resolveMode: %v", err)
	}
	if mode.prBranch == "" {
		t.Error("interactive fresh run should still cut a working branch")
	}
	if cfg.systemPrompt != "" {
		t.Errorf("interactive run should leave systemPrompt empty, got %q", cfg.systemPrompt)
	}
}

func TestCovModeRepoResuming(t *testing.T) {
	const resumeBranch = "issue-7-fix-abc123"

	t.Run("reuses the resumed branch and frames the default repo prompt", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, resumeBranch: resumeBranch, outputType: "pr"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != resumeBranch {
			t.Errorf("prBranch = %q, want the resumed branch %q", mode.prBranch, resumeBranch)
		}
		if mode.prTitle != "Bandolier agent changes" {
			t.Errorf("prTitle = %q", mode.prTitle)
		}
		if want := buildRepoSystemPrompt(resumeBranch); cfg.systemPrompt != want {
			t.Errorf("systemPrompt = %q, want buildRepoSystemPrompt(resumeBranch)", cfg.systemPrompt)
		}
	})

	t.Run("keeps a server-supplied system prompt untouched", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, resumeBranch: resumeBranch, outputType: "pr", systemPrompt: "server framing"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != resumeBranch {
			t.Errorf("prBranch = %q, want %q", mode.prBranch, resumeBranch)
		}
		if cfg.systemPrompt != "server framing" {
			t.Errorf("systemPrompt = %q, want the server framing preserved", cfg.systemPrompt)
		}
	})

	t.Run("interactive resume leaves the system prompt empty", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, resumeBranch: resumeBranch, outputType: "pr", interactive: true}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != resumeBranch {
			t.Errorf("prBranch = %q, want %q", mode.prBranch, resumeBranch)
		}
		if cfg.systemPrompt != "" {
			t.Errorf("interactive resume should leave systemPrompt empty, got %q", cfg.systemPrompt)
		}
	})
}

func TestCovModeRepoIssueOutput(t *testing.T) {
	t.Run("non-interactive sets the nil-parent analysis prompt, no branch", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, outputType: "issue"}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != "" {
			t.Errorf("prBranch = %q, want empty for issue output", mode.prBranch)
		}
		if !mode.issueOutput {
			t.Error("issueOutput = false, want true")
		}
		if want := buildIssueOutputSystemPrompt(nil); cfg.systemPrompt != want {
			t.Errorf("systemPrompt = %q, want buildIssueOutputSystemPrompt(nil)", cfg.systemPrompt)
		}
	})

	t.Run("interactive leaves the system prompt empty (framed in runAgent)", func(t *testing.T) {
		cfg := config{repoURL: covModeRepoURL, outputType: "issue", interactive: true}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != "" {
			t.Errorf("prBranch = %q, want empty for issue output", mode.prBranch)
		}
		if !mode.issueOutput {
			t.Error("issueOutput = false, want true")
		}
		if cfg.systemPrompt != "" {
			t.Errorf("interactive issue-output should leave systemPrompt empty, got %q", cfg.systemPrompt)
		}
	})
}

func TestCovModeIssuePR(t *testing.T) {
	covModeFakeIssueGh(t)
	cfg := config{
		issueNumber:  "42",
		task:         "do the work",
		agentBranch:  "issue-42-fix-abc123",
		systemPrompt: "server framing",
		outputType:   "pr",
		workDir:      t.TempDir(),
	}
	mode, err := resolveMode(context.Background(), &cfg)
	if err != nil {
		t.Fatalf("resolveMode: %v", err)
	}
	if mode.prBranch != "issue-42-fix-abc123" {
		t.Errorf("prBranch = %q, want the server-supplied AGENT_BRANCH", mode.prBranch)
	}
	if mode.prTitle != "Fix the flaky test" {
		t.Errorf("prTitle = %q, want the issue title", mode.prTitle)
	}
	if !strings.Contains(mode.prBody, "Closes #42") {
		t.Errorf("prBody = %q, want an issue-closing trailer", mode.prBody)
	}
	if mode.parentIssue == nil || mode.parentIssue.Number != 42 {
		t.Errorf("parentIssue = %+v, want the fetched issue #42", mode.parentIssue)
	}
	if mode.issueOutput {
		t.Error("issueOutput = true, want false for a PR-producing issue run")
	}
	if cfg.systemPrompt != "server framing" {
		t.Errorf("systemPrompt = %q, want the server framing preserved", cfg.systemPrompt)
	}
}

func TestCovModeIssueOutput(t *testing.T) {
	covModeFakeIssueGh(t)

	t.Run("empty framing gets the analysis prompt scoped to the parent", func(t *testing.T) {
		cfg := config{issueNumber: "42", task: "do the work", outputType: "issue", workDir: t.TempDir()}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if mode.prBranch != "" {
			t.Errorf("prBranch = %q, want empty for issue output", mode.prBranch)
		}
		if !mode.issueOutput {
			t.Error("issueOutput = false, want true")
		}
		if mode.parentIssue == nil || mode.parentIssue.Number != 42 {
			t.Fatalf("parentIssue = %+v, want #42", mode.parentIssue)
		}
		if want := buildIssueOutputSystemPrompt(mode.parentIssue); cfg.systemPrompt != want {
			t.Errorf("systemPrompt = %q, want buildIssueOutputSystemPrompt(parent)", cfg.systemPrompt)
		}
		if !strings.Contains(cfg.systemPrompt, "#42") {
			t.Errorf("issue-output framing should reference the parent #42, got %q", cfg.systemPrompt)
		}
	})

	t.Run("a server-supplied framing is left untouched", func(t *testing.T) {
		cfg := config{issueNumber: "42", task: "do the work", outputType: "issue", systemPrompt: "server issue framing", workDir: t.TempDir()}
		mode, err := resolveMode(context.Background(), &cfg)
		if err != nil {
			t.Fatalf("resolveMode: %v", err)
		}
		if !mode.issueOutput {
			t.Error("issueOutput = false, want true")
		}
		if cfg.systemPrompt != "server issue framing" {
			t.Errorf("systemPrompt = %q, want the server framing preserved", cfg.systemPrompt)
		}
	})
}

func TestCovModeIssueErrors(t *testing.T) {
	// fetchIssue succeeds here; each case exercises a post-fetch required-input
	// check in the PR (non-issue-output) issue-mode arm.
	covModeFakeIssueGh(t)

	cases := []struct {
		name    string
		cfg     config
		wantSub string
	}{
		{
			name:    "empty CLAUDE_TASK",
			cfg:     config{issueNumber: "42", task: "", agentBranch: "b", systemPrompt: "s", outputType: "pr"},
			wantSub: "CLAUDE_TASK is empty",
		},
		{
			name:    "empty AGENT_BRANCH",
			cfg:     config{issueNumber: "42", task: "x", agentBranch: "", systemPrompt: "s", outputType: "pr"},
			wantSub: "AGENT_BRANCH is empty",
		},
		{
			name:    "empty CLAUDE_SYSTEM_PROMPT",
			cfg:     config{issueNumber: "42", task: "x", agentBranch: "b", systemPrompt: "", outputType: "pr"},
			wantSub: "CLAUDE_SYSTEM_PROMPT is empty",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := tc.cfg
			cfg.workDir = t.TempDir()
			_, err := resolveMode(context.Background(), &cfg)
			if err == nil {
				t.Fatalf("resolveMode should error on %s", tc.name)
			}
			if !strings.Contains(err.Error(), tc.wantSub) {
				t.Errorf("error = %q, want it to mention %q", err.Error(), tc.wantSub)
			}
		})
	}
}

func TestCovModeIssueFetchError(t *testing.T) {
	// A non-zero gh exit propagates as a "fetch issue" error before any of the
	// required-input checks run.
	covGHFakeGh(t, "#!/bin/sh\necho 'gh: not authenticated' >&2\nexit 1\n")
	cfg := config{issueNumber: "42", task: "x", agentBranch: "b", systemPrompt: "s", outputType: "pr", workDir: t.TempDir()}
	_, err := resolveMode(context.Background(), &cfg)
	if err == nil {
		t.Fatal("resolveMode should error when gh fails")
	}
	if !strings.Contains(err.Error(), "fetch issue") {
		t.Errorf("error = %q, want it wrapped as a fetch-issue failure", err.Error())
	}
}

func TestCovModeGitIdentity(t *testing.T) {
	t.Run("falls back to the Bandolier identity when both are empty", func(t *testing.T) {
		name, email := gitIdentity(config{})
		if name != "Bandolier Agent" {
			t.Errorf("name = %q, want the fallback", name)
		}
		if email != "bandolier-agent@bandolier.local" {
			t.Errorf("email = %q, want the fallback", email)
		}
	})

	t.Run("returns the provided identity", func(t *testing.T) {
		name, email := gitIdentity(config{gitName: "Octo Cat", gitEmail: "octo@example.com"})
		if name != "Octo Cat" {
			t.Errorf("name = %q, want the provided value", name)
		}
		if email != "octo@example.com" {
			t.Errorf("email = %q, want the provided value", email)
		}
	})

	t.Run("falls back on each field independently", func(t *testing.T) {
		// Name supplied, email missing.
		name, email := gitIdentity(config{gitName: "Octo Cat"})
		if name != "Octo Cat" {
			t.Errorf("name = %q, want the provided value", name)
		}
		if email != "bandolier-agent@bandolier.local" {
			t.Errorf("email = %q, want the fallback", email)
		}
		// Email supplied, name missing.
		name, email = gitIdentity(config{gitEmail: "octo@example.com"})
		if name != "Bandolier Agent" {
			t.Errorf("name = %q, want the fallback", name)
		}
		if email != "octo@example.com" {
			t.Errorf("email = %q, want the provided value", email)
		}
	})
}

func TestCovModeOrSignal(t *testing.T) {
	t.Run("nil error returns nil regardless of ctx state", func(t *testing.T) {
		if err := orSignal(context.Background(), nil, "op"); err != nil {
			t.Errorf("orSignal(live, nil) = %v, want nil", err)
		}
		ctx, cancel := context.WithCancel(context.Background())
		cancel()
		if err := orSignal(ctx, nil, "op"); err != nil {
			t.Errorf("orSignal(cancelled, nil) = %v, want nil", err)
		}
	})

	t.Run("a cancelled ctx with an error is a clean signal stop", func(t *testing.T) {
		ctx, cancel := context.WithCancel(context.Background())
		cancel()
		err := orSignal(ctx, errors.New("boom"), "run agent")
		if !errors.Is(err, errSignaled) {
			t.Errorf("orSignal(cancelled, err) = %v, want errSignaled", err)
		}
	})

	t.Run("a live ctx wraps the error with the op label", func(t *testing.T) {
		base := errors.New("boom")
		err := orSignal(context.Background(), base, "run agent")
		if err == nil {
			t.Fatal("orSignal(live, err) = nil, want the wrapped error")
		}
		if !errors.Is(err, base) {
			t.Errorf("wrapped error should unwrap to the base error, got %v", err)
		}
		if errors.Is(err, errSignaled) {
			t.Error("a live-ctx error must not be reported as errSignaled")
		}
		if !strings.HasPrefix(err.Error(), "run agent: ") {
			t.Errorf("error = %q, want it prefixed with the op", err.Error())
		}
	})
}
