package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

func TestSlugify(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"Fix the login bug", "fix-the-login-bug"},
		{"Add   OAuth!! support", "add-oauth-support"},
		{"  !!hello!!  ", "hello"},
		{"UPPER case Title", "upper-case-title"},
		{"", "task"},
		{"!!!", "task"},
		// Truncated to <=24 chars with no trailing hyphen.
		{"this is a very long issue title that exceeds the limit", "this-is-a-very-long-issu"},
	}
	for _, c := range cases {
		if got := slugify(c.in); got != c.want {
			t.Errorf("slugify(%q) = %q, want %q", c.in, got, c.want)
		}
		if len(slugify(c.in)) > 24 {
			t.Errorf("slugify(%q) exceeds 24 chars", c.in)
		}
	}
}

func TestSlugifyNeverHasEdgeHyphens(t *testing.T) {
	// A title whose first 24 chars end mid-separator must not yield a trailing
	// hyphen after truncation.
	got := slugify("abcdefghijklmnopqrstuv!!extra")
	if strings.HasPrefix(got, "-") || strings.HasSuffix(got, "-") {
		t.Errorf("slugify produced edge hyphen: %q", got)
	}
}

func TestShortUnique(t *testing.T) {
	s := shortUnique()
	if len(s) != 6 {
		t.Errorf("shortUnique() = %q, want length 6", s)
	}
	if !regexp.MustCompile(`^[0-9a-z]{6}$`).MatchString(s) {
		t.Errorf("shortUnique() = %q, want base-36 chars", s)
	}
}

func TestRepoBranchName(t *testing.T) {
	got := repoBranchName("Add feature")
	re := regexp.MustCompile(`^bandolier/add-feature-[0-9a-z]{6}$`)
	if !re.MatchString(got) {
		t.Errorf("repoBranchName = %q, want match %v", got, re)
	}
}

func TestBuildRepoSystemPrompt(t *testing.T) {
	got := buildRepoSystemPrompt("bandolier/do-the-thing-abc123")
	if !strings.Contains(got, `on branch "bandolier/do-the-thing-abc123"`) {
		t.Error("buildRepoSystemPrompt should mention the branch")
	}
	if !strings.Contains(got, "git commit -s") {
		t.Error("buildRepoSystemPrompt should instruct a signed commit")
	}
	if !strings.Contains(got, "Do NOT push or open a pull request") {
		t.Error("buildRepoSystemPrompt should forbid pushing")
	}
	if !strings.Contains(got, "commit-by-commit") {
		t.Error("buildRepoSystemPrompt should ask for a reviewable, commit-by-commit history")
	}
}

func TestBuildInteractiveSystemPrompt(t *testing.T) {
	got := buildInteractiveSystemPrompt("bandolier/chat-abc123")
	if !strings.Contains(got, "interactive session") {
		t.Error("should describe the interactive session")
	}
	if !strings.Contains(got, `on branch "bandolier/chat-abc123"`) {
		t.Error("should mention the working branch")
	}
	if buildInteractiveSystemPrompt("") != "" {
		t.Error("should be empty when there's no working branch")
	}
}

func TestParsePRContent(t *testing.T) {
	out := "TITLE: Add retry logic\nBODY:\nThis adds retries.\n\n## Changes\n- retry on 500"
	title, body := parsePRContent(out)
	if title != "Add retry logic" {
		t.Errorf("title = %q", title)
	}
	if !strings.HasPrefix(body, "This adds retries.") {
		t.Errorf("body = %q", body)
	}
	if !strings.Contains(body, "## Changes") {
		t.Errorf("body should retain markdown sections, got %q", body)
	}
}

func TestParsePRContentNoTitle(t *testing.T) {
	title, body := parsePRContent("just some text with no markers")
	if title != "" || body != "" {
		t.Errorf("expected empty title/body, got (%q, %q)", title, body)
	}
}

func TestParsePRContentTitleOnly(t *testing.T) {
	title, body := parsePRContent("TITLE: Only a title")
	if title != "Only a title" {
		t.Errorf("title = %q", title)
	}
	if body != "" {
		t.Errorf("body = %q, want empty", body)
	}
}

func TestEnsureCloses(t *testing.T) {
	t.Run("prepends closing keyword when absent", func(t *testing.T) {
		got := ensureCloses("Some description.", "42")
		if !strings.HasPrefix(got, "Closes #42") {
			t.Errorf("got %q", got)
		}
		if !strings.Contains(got, "Some description.") {
			t.Error("original body should be preserved")
		}
	})

	t.Run("is idempotent when closing keyword already present", func(t *testing.T) {
		body := "Closes #42\n\nDetails here."
		if got := ensureCloses(body, "42"); got != body {
			t.Errorf("ensureCloses changed an already-closing body: %q", got)
		}
	})

	t.Run("matches the keyword case-insensitively", func(t *testing.T) {
		body := "closes #42 in the description"
		if got := ensureCloses(body, "42"); got != body {
			t.Errorf("should treat lowercase 'closes' as present, got %q", got)
		}
	})

	t.Run("synthesizes a body when empty", func(t *testing.T) {
		got := ensureCloses("   ", "42")
		if !strings.Contains(got, "Closes #42") {
			t.Errorf("got %q", got)
		}
		if !strings.Contains(got, "Generated by Bandolier.") {
			t.Errorf("got %q", got)
		}
	})
}

func TestEnsurePartOf(t *testing.T) {
	t.Run("prepends parent reference when absent", func(t *testing.T) {
		got := ensurePartOf("Some description.", 42)
		if !strings.HasPrefix(got, "Part of #42") {
			t.Errorf("got %q", got)
		}
		if !strings.Contains(got, "Some description.") {
			t.Error("original body should be preserved")
		}
	})

	t.Run("is idempotent when parent reference already present", func(t *testing.T) {
		body := "Part of #42\n\nDetails here."
		if got := ensurePartOf(body, 42); got != body {
			t.Errorf("ensurePartOf changed an already-referencing body: %q", got)
		}
	})

	t.Run("matches the reference case-insensitively", func(t *testing.T) {
		body := "part of #42 in the description"
		if got := ensurePartOf(body, 42); got != body {
			t.Errorf("should treat lowercase 'part of' as present, got %q", got)
		}
	})

	t.Run("synthesizes a body when empty", func(t *testing.T) {
		got := ensurePartOf("   ", 42)
		if !strings.Contains(got, "Part of #42") {
			t.Errorf("got %q", got)
		}
		if !strings.Contains(got, "Generated by Bandolier.") {
			t.Errorf("got %q", got)
		}
	})
}

func TestPRURLRe(t *testing.T) {
	t.Run("scrapes the created-PR URL from gh stdout", func(t *testing.T) {
		out := "https://github.com/owner/repo/pull/123\n"
		if got := prURLRe.FindString(out); got != "https://github.com/owner/repo/pull/123" {
			t.Errorf("got %q", got)
		}
	})

	t.Run("scrapes the URL from an already-exists notice", func(t *testing.T) {
		out := "a pull request for branch \"feat\" into branch \"main\" already exists:\n" +
			"https://github.com/owner/repo/pull/7\n"
		if got := prURLRe.FindString(out); got != "https://github.com/owner/repo/pull/7" {
			t.Errorf("got %q", got)
		}
	})

	t.Run("does not match an issue URL", func(t *testing.T) {
		if got := prURLRe.FindString("https://github.com/owner/repo/issues/9"); got != "" {
			t.Errorf("prURLRe matched an issue URL: %q", got)
		}
	})
}

func TestIssueURLRe(t *testing.T) {
	t.Run("scrapes the created-issue URL from gh stdout", func(t *testing.T) {
		out := "https://github.com/owner/repo/issues/456\n"
		if got := issueURLRe.FindString(out); got != "https://github.com/owner/repo/issues/456" {
			t.Errorf("got %q", got)
		}
	})

	t.Run("does not match a PR URL", func(t *testing.T) {
		if got := issueURLRe.FindString("https://github.com/owner/repo/pull/9"); got != "" {
			t.Errorf("issueURLRe matched a PR URL: %q", got)
		}
	})
}

func TestClassifyPRCreate(t *testing.T) {
	t.Run("created: scrapes URL, no error, not already-exists", func(t *testing.T) {
		res := classifyPRCreate("https://github.com/owner/repo/pull/123\n", nil)
		if res.err != nil {
			t.Errorf("unexpected err: %v", res.err)
		}
		if res.alreadyExists {
			t.Error("should not be flagged as already-exists")
		}
		if res.url != "https://github.com/owner/repo/pull/123" {
			t.Errorf("got url %q", res.url)
		}
	})

	t.Run("already exists: idempotent success with scraped URL", func(t *testing.T) {
		out := "a pull request for branch \"feat\" into branch \"main\" already exists:\n" +
			"https://github.com/owner/repo/pull/7\n"
		res := classifyPRCreate(out, errors.New("exit status 1"))
		if res.err != nil {
			t.Errorf("already-exists should not propagate an error, got: %v", res.err)
		}
		if !res.alreadyExists {
			t.Error("should be flagged as already-exists")
		}
		if res.url != "https://github.com/owner/repo/pull/7" {
			t.Errorf("got url %q", res.url)
		}
	})

	t.Run("genuine failure: propagates error", func(t *testing.T) {
		res := classifyPRCreate("HTTP 403: Resource not accessible by integration\n", errors.New("exit status 1"))
		if res.err == nil {
			t.Fatal("expected an error to be propagated")
		}
		if !strings.Contains(res.err.Error(), "gh pr create") {
			t.Errorf("error should be wrapped, got %q", res.err)
		}
		if res.alreadyExists {
			t.Error("should not be flagged as already-exists")
		}
	})
}

func TestBuildIssuePrompt(t *testing.T) {
	t.Run("keeps the tail when transcript exceeds the cap", func(t *testing.T) {
		head := strings.Repeat("H", maxIssueTranscriptBytes)
		tail := "THE-WRITEUP-AT-THE-END"
		transcript := head + tail
		got := buildIssuePrompt(transcript, nil)
		if !strings.Contains(got, "transcript truncated") {
			t.Error("expected a truncation marker")
		}
		if !strings.Contains(got, tail) {
			t.Error("the tail of the transcript should be kept")
		}
		if strings.Contains(got, head) {
			t.Error("the head should be dropped, not the tail")
		}
	})

	t.Run("does not truncate a short transcript", func(t *testing.T) {
		got := buildIssuePrompt("short transcript", nil)
		if strings.Contains(got, "transcript truncated") {
			t.Error("short transcript should not be truncated")
		}
		if !strings.Contains(got, "short transcript") {
			t.Error("transcript should be included")
		}
	})

	t.Run("references the parent issue when present", func(t *testing.T) {
		got := buildIssuePrompt("t", &githubIssue{Number: 42, Title: "Parent"})
		if !strings.Contains(got, "#42") {
			t.Errorf("expected the parent number, got %q", got)
		}
	})
}

func TestSetEnvIfMissing(t *testing.T) {
	t.Run("adds a key that is absent", func(t *testing.T) {
		env := setEnvIfMissing([]string{"FOO=1"}, "BAR", "2")
		if !containsEnv(env, "BAR=2") {
			t.Errorf("BAR not added: %v", env)
		}
	})

	t.Run("leaves an existing key untouched", func(t *testing.T) {
		env := setEnvIfMissing([]string{"BAR=original"}, "BAR", "new")
		if !containsEnv(env, "BAR=original") || containsEnv(env, "BAR=new") {
			t.Errorf("existing BAR should be preserved: %v", env)
		}
	})
}

func TestBackendPrefixGollm(t *testing.T) {
	// Every proxied provider is named by BANDOLIER_LLM_PROVIDER; the backend
	// prefix is that id verbatim, and the harness materializes nothing — the
	// server injects each backend's credential env vars (a bare key here, an
	// inline auth.json for chatgpt, inline service-account JSON for vertex).
	cases := []string{"openai", "chatgpt", "gemini", "vertex", "openrouter"}
	for _, backend := range cases {
		t.Run(backend, func(t *testing.T) {
			t.Setenv("BANDOLIER_LLM_PROVIDER", backend)
			got, err := backendPrefix(config{provider: providerGollm})
			if err != nil || got != backend {
				t.Fatalf("backendPrefix = %q, %v, want %q", got, err, backend)
			}
			if want := "gollm:" + backend; providerGollm.String() != want {
				t.Errorf("providerGollm.String() = %q, want %q", providerGollm.String(), want)
			}
		})
	}
}

func TestBackendPrefixRejectsNonGollm(t *testing.T) {
	if _, err := backendPrefix(config{provider: providerAnthropic}); err == nil {
		t.Error("backendPrefix should error for a native (non-proxied) provider")
	}
}

func TestModelList(t *testing.T) {
	// Task + writer models get their own aliases; the claude-* wildcard catches
	// the claude CLI's internal background calls and lands on the cheap model.
	list := modelList(config{model: "gpt-5.5", prWriter: "gpt-5.4-mini"}, "openai")
	byAlias := map[string]string{}
	for _, e := range list {
		byAlias[e.ModelName] = e.Params.Model
	}
	want := map[string]string{
		"gpt-5.5":      "openai/gpt-5.5",
		"gpt-5.4-mini": "openai/gpt-5.4-mini",
		"claude-*":     "openai/gpt-5.4-mini",
	}
	if len(byAlias) != len(want) {
		t.Fatalf("model list = %v, want %v", byAlias, want)
	}
	for alias, model := range want {
		if byAlias[alias] != model {
			t.Errorf("alias %s = %q, want %q", alias, byAlias[alias], model)
		}
	}

	// Without a distinct writer, the task model serves everything.
	list = modelList(config{model: "gpt-5.5"}, "openai")
	if len(list) != 2 || list[1].ModelName != "claude-*" || list[1].Params.Model != "openai/gpt-5.5" {
		t.Errorf("writerless model list = %+v", list)
	}
}

func TestStartModelProxyServesAnthropicSurface(t *testing.T) {
	// Full integration: start the embedded proxy for a proxied (OpenAI) run and
	// check it exports the claude CLI's env and serves the authenticated
	// Anthropic-format surface on localhost.
	t.Setenv("BANDOLIER_LLM_PROVIDER", "openai")
	t.Setenv("OPENAI_API_KEY", "sk-test")
	t.Setenv("ANTHROPIC_BASE_URL", "")
	t.Setenv("ANTHROPIC_AUTH_TOKEN", "")
	t.Setenv("ANTHROPIC_SMALL_FAST_MODEL", "")

	stop, err := startModelProxy(config{provider: providerGollm, model: "gpt-5.5", prWriter: "gpt-5.4-mini"})
	if err != nil {
		t.Fatalf("startModelProxy: %v", err)
	}
	defer stop()

	base := os.Getenv("ANTHROPIC_BASE_URL")
	token := os.Getenv("ANTHROPIC_AUTH_TOKEN")
	if !strings.HasPrefix(base, "http://127.0.0.1:") {
		t.Fatalf("ANTHROPIC_BASE_URL = %q, want a localhost URL", base)
	}
	if token == "" {
		t.Fatal("ANTHROPIC_AUTH_TOKEN not exported")
	}
	if got := os.Getenv("ANTHROPIC_SMALL_FAST_MODEL"); got != "gpt-5.4-mini" {
		t.Errorf("ANTHROPIC_SMALL_FAST_MODEL = %q, want the writer model", got)
	}

	// Without the key the proxy must refuse; with it, the aliases are served.
	unauth, err := http.Get(base + "/v1/models")
	if err != nil {
		t.Fatal(err)
	}
	unauth.Body.Close()
	if unauth.StatusCode != http.StatusUnauthorized {
		t.Errorf("unauthenticated /v1/models = %d, want 401", unauth.StatusCode)
	}

	req, _ := http.NewRequest(http.MethodGet, base+"/v1/models", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("authenticated /v1/models = %d: %s", resp.StatusCode, body)
	}
	for _, alias := range []string{"gpt-5.5", "gpt-5.4-mini", "claude-*"} {
		if !strings.Contains(string(body), alias) {
			t.Errorf("/v1/models missing alias %s: %s", alias, body)
		}
	}
}

func TestLogUserInput(t *testing.T) {
	// logUserInput writes through the log package; capture that output and drop
	// the timestamp/flags so we assert only the tagged content.
	var buf bytes.Buffer
	origOut := log.Writer()
	origFlags := log.Flags()
	log.SetOutput(&buf)
	log.SetFlags(0)
	defer func() {
		log.SetOutput(origOut)
		log.SetFlags(origFlags)
	}()

	logUserInput("first line\nsecond line")

	got := buf.String()
	want := "[user] first line\n[user] second line\n"
	if got != want {
		t.Errorf("logUserInput output = %q, want %q", got, want)
	}
}

func TestRewriteCommitAuthors(t *testing.T) {
	dir := t.TempDir()

	git := func(args ...string) string {
		t.Helper()
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		// A clean, deterministic identity for the seed commits we then rewrite.
		cmd.Env = append(os.Environ(),
			"GIT_AUTHOR_NAME=Claude", "GIT_AUTHOR_EMAIL=noreply@anthropic.com",
			"GIT_COMMITTER_NAME=Claude", "GIT_COMMITTER_EMAIL=noreply@anthropic.com",
		)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
		}
		return strings.TrimSpace(string(out))
	}

	// A bare "origin" the working repo treats as its remote, so origin/main
	// resolves the way the harness expects in the pod.
	remote := t.TempDir()
	cmdRun(t, remote, "git", "init", "--bare", "-b", "main")

	cmdRun(t, dir, "git", "init", "-b", "main")
	git("remote", "add", "origin", remote)
	// Base commit on main.
	if err := os.WriteFile(filepath.Join(dir, "base.txt"), []byte("base"), 0o644); err != nil {
		t.Fatal(err)
	}
	git("add", "-A")
	git("commit", "-m", "base commit")
	git("push", "origin", "main")

	// Work branch with two commits: one carrying a Claude co-author trailer, one
	// authored entirely as Claude.
	git("checkout", "-b", "work")
	if err := os.WriteFile(filepath.Join(dir, "a.txt"), []byte("a"), 0o644); err != nil {
		t.Fatal(err)
	}
	git("add", "-A")
	git("commit", "-m", "first change\n\nCo-authored-by: Claude <noreply@anthropic.com>")
	if err := os.WriteFile(filepath.Join(dir, "b.txt"), []byte("b"), 0o644); err != nil {
		t.Fatal(err)
	}
	git("add", "-A")
	git("commit", "-m", "second change")

	cfg := config{workDir: dir, baseBranch: "main"}
	if err := rewriteCommitAuthors(context.Background(), cfg, "work", "octocat", "1+octocat@users.noreply.github.com"); err != nil {
		t.Fatalf("rewriteCommitAuthors: %v", err)
	}

	// Both new commits must now be authored and committed by the OAuth identity.
	idents := git("log", "origin/main..work", "--pretty=format:%an|%ae|%cn|%ce")
	for _, line := range strings.Split(idents, "\n") {
		if line != "octocat|1+octocat@users.noreply.github.com|octocat|1+octocat@users.noreply.github.com" {
			t.Errorf("commit identity not rewritten: %q", line)
		}
	}

	// The Claude co-author trailer must be gone from every commit message.
	msgs := git("log", "origin/main..work", "--pretty=format:%B")
	if strings.Contains(strings.ToLower(msgs), "anthropic") || strings.Contains(strings.ToLower(msgs), "co-authored-by: claude") {
		t.Errorf("Claude co-author trailer survived rewrite:\n%s", msgs)
	}
	// The real commit subjects must survive.
	if !strings.Contains(msgs, "first change") || !strings.Contains(msgs, "second change") {
		t.Errorf("commit subjects lost in rewrite:\n%s", msgs)
	}
}

func TestRewriteCommitAuthorsNoCommits(t *testing.T) {
	dir := t.TempDir()
	remote := t.TempDir()
	cmdRun(t, remote, "git", "init", "--bare", "-b", "main")
	cmdRun(t, dir, "git", "init", "-b", "main")
	cmdRun(t, dir, "git", "-c", "user.name=x", "-c", "user.email=x@x",
		"remote", "add", "origin", remote)
	cmdRun(t, dir, "git", "-c", "user.name=x", "-c", "user.email=x@x",
		"commit", "--allow-empty", "-m", "base")
	cmdRun(t, dir, "git", "push", "origin", "main")

	// Branch with no commits over the base — a no-op, no error.
	cmdRun(t, dir, "git", "checkout", "-b", "work")
	cfg := config{workDir: dir, baseBranch: "main"}
	if err := rewriteCommitAuthors(context.Background(), cfg, "work", "octocat", "o@x"); err != nil {
		t.Fatalf("rewriteCommitAuthors on empty branch should be a no-op: %v", err)
	}
}

// seedRemote creates a bare origin with a `main` branch (one commit) and a
// `work` branch on top of it, returning the bare repo's path.
func seedRemote(t *testing.T) string {
	t.Helper()
	seed := t.TempDir()
	remote := t.TempDir()
	cmdRun(t, remote, "git", "init", "--bare", "-b", "main")
	cmdRun(t, seed, "git", "init", "-b", "main")
	cmdRun(t, seed, "git", "remote", "add", "origin", remote)
	cmdRun(t, seed, "git", "-c", "user.name=x", "-c", "user.email=x@x",
		"commit", "--allow-empty", "-m", "base")
	cmdRun(t, seed, "git", "checkout", "-b", "work")
	cmdRun(t, seed, "git", "-c", "user.name=x", "-c", "user.email=x@x",
		"commit", "--allow-empty", "-m", "work commit")
	cmdRun(t, seed, "git", "push", "origin", "main", "work")
	return remote
}

func TestEnsureDiffBaseNoOpWhenPresent(t *testing.T) {
	remote := seedRemote(t)
	dir := t.TempDir()
	// A plain clone holds every remote ref, origin/main included.
	cmdRun(t, dir, "git", "clone", remote, ".")

	cfg := config{workDir: dir, baseBranch: "main"}
	if err := ensureDiffBase(context.Background(), cfg); err != nil {
		t.Fatalf("ensureDiffBase with the ref present: %v", err)
	}
}

func TestEnsureDiffBaseFetchesMissingRef(t *testing.T) {
	remote := seedRemote(t)
	dir := t.TempDir()
	// The pod's clone shape: --depth=1 --branch <work> is single-branch, so
	// origin/main does not exist locally — the state that made filter-branch
	// die on "unknown revision" before this step existed.
	cmdRun(t, dir, "git", "clone", "--depth=1", "--branch", "work", remote, ".")
	if err := exec.Command("git", "-C", dir, "rev-parse", "--verify", "--quiet", "origin/main^{commit}").Run(); err == nil {
		t.Fatal("test setup: origin/main should be absent from a single-branch clone")
	}

	cfg := config{workDir: dir, baseBranch: "main"}
	if err := ensureDiffBase(context.Background(), cfg); err != nil {
		t.Fatalf("ensureDiffBase should fetch the missing base: %v", err)
	}
	if err := exec.Command("git", "-C", dir, "rev-parse", "--verify", "--quiet", "origin/main^{commit}").Run(); err != nil {
		t.Fatalf("origin/main still unresolvable after ensureDiffBase: %v", err)
	}
}

func TestEnsureDiffBaseFailsClearlyWhenUnfetchable(t *testing.T) {
	remote := seedRemote(t)
	dir := t.TempDir()
	cmdRun(t, dir, "git", "clone", "--depth=1", "--branch", "work", remote, ".")

	// A base branch the remote doesn't have: the fetch fails, and the error
	// must name the ref so the failure is diagnosable from the pod log.
	cfg := config{workDir: dir, baseBranch: "no-such-branch"}
	err := ensureDiffBase(context.Background(), cfg)
	if err == nil {
		t.Fatal("ensureDiffBase should fail for a branch the remote lacks")
	}
	if !strings.Contains(err.Error(), "origin/no-such-branch") {
		t.Errorf("error should name the missing ref, got: %v", err)
	}
}

// cmdRun runs a command in dir, failing the test on error.
func cmdRun(t *testing.T, dir string, name string, args ...string) {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("%s %s: %v\n%s", name, strings.Join(args, " "), err, out)
	}
}

func containsEnv(env []string, want string) bool {
	for _, e := range env {
		if e == want {
			return true
		}
	}
	return false
}

func TestToolSummary(t *testing.T) {
	cases := []struct {
		name  string
		tool  string
		input string
		want  string
	}{
		{"bash command", "Bash", `{"command":"ls -la"}`, "Bash: ls -la"},
		{"file path", "Read", `{"file_path":"/tmp/x"}`, "Read: /tmp/x"},
		{"pattern in path", "Grep", `{"pattern":"foo","path":"src"}`, "Grep: foo in src"},
		{"path only", "LS", `{"path":"src"}`, "LS: src"},
		{"pattern only", "Glob", `{"pattern":"*.go"}`, "Glob: *.go"},
		{"url", "WebFetch", `{"url":"https://x.com"}`, "WebFetch: https://x.com"},
		{"query", "WebSearch", `{"query":"golang"}`, "WebSearch: golang"},
		{"empty input falls back to name", "Foo", `{}`, "Foo"},
		{"invalid json falls back to name", "Foo", `not json`, "Foo"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := toolSummary(c.tool, json.RawMessage(c.input))
			if got != c.want {
				t.Errorf("toolSummary(%q, %s) = %q, want %q", c.tool, c.input, got, c.want)
			}
		})
	}
}

func TestToolSummaryUnknownShape(t *testing.T) {
	// A tool input with only unrecognized keys serializes the full map.
	got := toolSummary("Custom", json.RawMessage(`{"foo":"bar"}`))
	if !strings.HasPrefix(got, "Custom: ") || !strings.Contains(got, "foo") {
		t.Errorf("unexpected fallback rendering: %q", got)
	}
}

func TestDetectProvider(t *testing.T) {
	// Clear the vars detectProvider inspects, then assert each selection path.
	for _, k := range []string{"CLAUDE_CODE_USE_BEDROCK", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "ANTHROPIC_API_KEY", "CLAUDE_CODE_OAUTH_TOKEN", "BANDOLIER_LLM_PROVIDER"} {
		t.Setenv(k, "")
	}
	if got := detectProvider(); got != providerNone {
		t.Errorf("no env → %v, want providerNone", got)
	}

	// Every proxied provider is selected by BANDOLIER_LLM_PROVIDER, regardless
	// of which backend it names (openai, chatgpt, gemini, vertex, groq, …).
	t.Setenv("BANDOLIER_LLM_PROVIDER", "groq")
	if got := detectProvider(); got != providerGollm {
		t.Errorf("BANDOLIER_LLM_PROVIDER set → %v, want providerGollm", got)
	}

	// A native credential takes its own path even when BANDOLIER_LLM_PROVIDER
	// is also set (the server never sets both, but native must win).
	t.Setenv("CLAUDE_CODE_OAUTH_TOKEN", "sk-ant-oat01-x")
	if got := detectProvider(); got != providerAnthropic {
		t.Errorf("CLAUDE_CODE_OAUTH_TOKEN set → %v, want providerAnthropic", got)
	}
	t.Setenv("CLAUDE_CODE_OAUTH_TOKEN", "")

	t.Setenv("CLAUDE_CODE_USE_BEDROCK", "1")
	if got := detectProvider(); got != providerBedrock {
		t.Errorf("USE_BEDROCK=1 → %v, want providerBedrock", got)
	}

	t.Setenv("CLAUDE_CODE_USE_BEDROCK", "")
	t.Setenv("ANTHROPIC_API_KEY", "sk-ant-x")
	if got := detectProvider(); got != providerAnthropic {
		t.Errorf("ANTHROPIC_API_KEY → %v, want providerAnthropic", got)
	}

	t.Setenv("AWS_ACCESS_KEY_ID", "AKIA")
	t.Setenv("AWS_SECRET_ACCESS_KEY", "secret")
	if got := detectProvider(); got != providerBedrock {
		t.Errorf("AWS keys take precedence → %v, want providerBedrock", got)
	}
}

func TestNormalizeEffort(t *testing.T) {
	for _, level := range []string{"low", "medium", "high", "xhigh", "max"} {
		if got := normalizeEffort(level); got != level {
			t.Errorf("normalizeEffort(%q) = %q, want %q", level, got, level)
		}
	}

	// Case-insensitive and trimmed.
	if got := normalizeEffort("  HIGH "); got != "high" {
		t.Errorf("normalizeEffort(\"  HIGH \") = %q, want \"high\"", got)
	}

	// Unknown values drop to empty so the CLI default is used.
	for _, bad := range []string{"", "turbo", "highest", "1"} {
		if got := normalizeEffort(bad); got != "" {
			t.Errorf("normalizeEffort(%q) = %q, want \"\"", bad, got)
		}
	}
}

func TestWithParentContext(t *testing.T) {
	// No transcript → the task is untouched.
	if got := withParentContext("do the thing", ""); got != "do the thing" {
		t.Errorf("withParentContext with empty transcript = %q, want the task unchanged", got)
	}

	// Transcript and follow-up request both present, in order.
	got := withParentContext("fix the tests", "parent did X")
	if !strings.Contains(got, "<parent-run-transcript>\nparent did X\n</parent-run-transcript>") {
		t.Errorf("transcript not embedded between markers:\n%s", got)
	}
	if !strings.HasSuffix(got, "## Follow-up request\n\nfix the tests") {
		t.Errorf("task not appended as the follow-up request:\n%s", got)
	}

	// Oversized transcripts keep the tail (the parent's final state) and flag
	// the truncation.
	huge := strings.Repeat("a", maxParentContextBytes) + "THE-END"
	got = withParentContext("task", huge)
	if !strings.Contains(got, "…(earlier transcript truncated)…") {
		t.Error("truncation marker missing for oversized transcript")
	}
	if !strings.Contains(got, "THE-END") {
		t.Error("tail of oversized transcript was dropped")
	}
	if strings.Contains(got, strings.Repeat("a", maxParentContextBytes)) {
		t.Error("oversized transcript was not truncated")
	}
}

func TestDiffBase(t *testing.T) {
	normal := config{baseBranch: "main"}
	if got := normal.diffBase(); got != "origin/main" {
		t.Errorf("diffBase() = %q, want origin/main", got)
	}
	// Resumed runs measure new work against the resumed branch's remote tip,
	// not the PR base — already-pushed commits must stay untouched.
	resumed := config{baseBranch: "main", resumeBranch: "issue-7-fix-abc123"}
	if got := resumed.diffBase(); got != "origin/issue-7-fix-abc123" {
		t.Errorf("diffBase() on resume = %q, want origin/issue-7-fix-abc123", got)
	}
}

// clearConfigEnv zeroes every environment variable loadConfig reads so a test's
// t.Setenv calls define the whole input — otherwise the runner's own
// environment (e.g. a real CLAUDE_MODEL) would leak into the result.
func clearConfigEnv(t *testing.T) {
	for _, k := range []string{
		"GITHUB_ISSUE_NUMBER", "CLAUDE_TASK", "WORKING_DIR", "CLAUDE_MODEL",
		"CLAUDE_EFFORT", "MAX_TURNS", "GITHUB_BASE_BRANCH", "BRANCH", "OUTPUT_TYPE",
		"CLAUDE_SYSTEM_PROMPT", "REPO_SYSTEM_PROMPT", "AGENT_TITLE", "PR_WRITER_MODEL",
		"REPO_URL", "GIT_NAME", "GIT_EMAIL", "GITHUB_REPO", "AGENT_BRANCH",
		"INTERACTIVE", "BANDOLIER_INPUT_URL", "BANDOLIER_ACP_URL", "RESUME_BRANCH",
		"BANDOLIER_CONTEXT_URL", "REVIEW_PR_NUMBER", "BANDOLIER_REVIEW_URL",
	} {
		t.Setenv(k, "")
	}
}

func TestLoadConfigRequiresTaskOrIssue(t *testing.T) {
	clearConfigEnv(t)
	if _, err := loadConfig(); err == nil {
		t.Fatal("loadConfig() with empty CLAUDE_TASK and GITHUB_ISSUE_NUMBER = nil error, want error")
	}

	// Issue mode: an empty task is fine as long as an issue number is present.
	clearConfigEnv(t)
	t.Setenv("GITHUB_ISSUE_NUMBER", "42")
	c, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() in issue mode = %v, want nil", err)
	}
	if c.task != "" {
		t.Errorf("issue-mode task = %q, want empty", c.task)
	}
	if c.issueNumber != "42" {
		t.Errorf("issueNumber = %q, want 42", c.issueNumber)
	}

	// Whitespace-only CLAUDE_TASK trims to empty, so issue mode must still carry
	// the run rather than erroring on the blank task.
	clearConfigEnv(t)
	t.Setenv("GITHUB_ISSUE_NUMBER", "7")
	t.Setenv("CLAUDE_TASK", "   \t  ")
	c, err = loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() whitespace task in issue mode = %v, want nil", err)
	}
	if c.task != "" {
		t.Errorf("whitespace task = %q, want empty after trim", c.task)
	}

	// Whitespace-only task with no issue number still fails: the trim leaves it
	// empty and the required-input check fires.
	clearConfigEnv(t)
	t.Setenv("CLAUDE_TASK", "   \n ")
	if _, err := loadConfig(); err == nil {
		t.Fatal("loadConfig() with whitespace-only task and no issue = nil error, want error")
	}
}

func TestLoadConfigBaseBranchFallback(t *testing.T) {
	tests := []struct {
		name       string
		githubBase string
		branch     string
		want       string
	}{
		{"github base wins", "release", "feature", "release"},
		{"falls back to BRANCH", "", "feature", "feature"},
		{"defaults to main", "", "", "main"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			clearConfigEnv(t)
			t.Setenv("CLAUDE_TASK", "do a thing")
			t.Setenv("GITHUB_BASE_BRANCH", tt.githubBase)
			t.Setenv("BRANCH", tt.branch)
			c, err := loadConfig()
			if err != nil {
				t.Fatalf("loadConfig() = %v, want nil", err)
			}
			if c.baseBranch != tt.want {
				t.Errorf("baseBranch = %q, want %q", c.baseBranch, tt.want)
			}
		})
	}
}

func TestLoadConfigDefaults(t *testing.T) {
	clearConfigEnv(t)
	t.Setenv("CLAUDE_TASK", "do a thing")
	c, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() = %v, want nil", err)
	}
	if c.workDir != "/workspace" {
		t.Errorf("workDir = %q, want /workspace", c.workDir)
	}
	if c.model != "claude-sonnet-4-6" {
		t.Errorf("model = %q, want claude-sonnet-4-6", c.model)
	}
	// Mirrors the server's DEFAULT_MAX_TURNS (Number.MAX_SAFE_INTEGER).
	if c.maxTurns != "9007199254740991" {
		t.Errorf("maxTurns = %q, want 9007199254740991", c.maxTurns)
	}
	if c.outputType != "pr" {
		t.Errorf("outputType = %q, want pr", c.outputType)
	}
	if c.interactive {
		t.Error("interactive = true, want false by default")
	}
	if c.task != "do a thing" {
		t.Errorf("task = %q, want %q", c.task, "do a thing")
	}
}

func TestLoadConfigInteractiveExactMatch(t *testing.T) {
	tests := []struct {
		value string
		want  bool
	}{
		{"1", true},
		{"0", false},
		{"true", false},
		{"", false},
	}
	for _, tt := range tests {
		t.Run(tt.value, func(t *testing.T) {
			clearConfigEnv(t)
			t.Setenv("CLAUDE_TASK", "do a thing")
			t.Setenv("INTERACTIVE", tt.value)
			c, err := loadConfig()
			if err != nil {
				t.Fatalf("loadConfig() = %v, want nil", err)
			}
			if c.interactive != tt.want {
				t.Errorf("interactive for INTERACTIVE=%q = %v, want %v", tt.value, c.interactive, tt.want)
			}
		})
	}
}

func TestLoadConfigResumeBranchTrimmed(t *testing.T) {
	clearConfigEnv(t)
	t.Setenv("CLAUDE_TASK", "do a thing")
	t.Setenv("RESUME_BRANCH", "  issue-7-fix-abc123\n")
	c, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() = %v, want nil", err)
	}
	if c.resumeBranch != "issue-7-fix-abc123" {
		t.Errorf("resumeBranch = %q, want trimmed %q", c.resumeBranch, "issue-7-fix-abc123")
	}
}

func TestWithRepoPrompt(t *testing.T) {
	// Empty everywhere → empty.
	if got := (config{}).withRepoPrompt(""); got != "" {
		t.Errorf("all-empty withRepoPrompt() = %q, want empty", got)
	}

	// Only the framing survives when there's no repo/serena layer.
	if got := (config{}).withRepoPrompt("frame"); got != "frame" {
		t.Errorf("framing-only withRepoPrompt() = %q, want %q", got, "frame")
	}

	// Layers are appended in order: framing, repo prompt, then serena override.
	c := config{repoSystemPrompt: "repo", serenaPrompt: "serena"}
	want := "frame\n\nrepo\n\nserena"
	if got := c.withRepoPrompt("frame"); got != want {
		t.Errorf("layered withRepoPrompt() = %q, want %q", got, want)
	}

	// A missing middle layer is skipped without leaving a blank gap.
	c = config{serenaPrompt: "serena"}
	want = "frame\n\nserena"
	if got := c.withRepoPrompt("frame"); got != want {
		t.Errorf("serena-only withRepoPrompt() = %q, want %q", got, want)
	}

	// A highest-effort Claude run appends the ultracode framing last; a
	// below-highest Claude run and a non-Claude highest-effort run do not.
	c = config{provider: providerAnthropic, effort: highestEffort}
	if got := c.withRepoPrompt("frame"); got != "frame\n\n"+ultracodeFraming {
		t.Errorf("ultracode withRepoPrompt() = %q, want ultracode appended", got)
	}
	c = config{provider: providerAnthropic, effort: "high"}
	if got := c.withRepoPrompt("frame"); got != "frame" {
		t.Errorf("below-highest withRepoPrompt() = %q, want no ultracode", got)
	}
	c = config{provider: providerGollm, effort: highestEffort}
	if got := c.withRepoPrompt("frame"); got != "frame" {
		t.Errorf("non-Claude highest-effort withRepoPrompt() = %q, want no ultracode", got)
	}
}

func TestUltracode(t *testing.T) {
	// Only a Claude provider at the highest effort level enters ultracode.
	for _, p := range []providerKind{providerAnthropic, providerBedrock} {
		if !(config{provider: p, effort: highestEffort}).ultracode() {
			t.Errorf("ultracode() = false for Claude provider %d at highest effort, want true", p)
		}
		if (config{provider: p, effort: "high"}).ultracode() {
			t.Errorf("ultracode() = true for Claude provider %d below highest, want false", p)
		}
	}
	// Non-Claude providers never enter ultracode, even at the highest effort.
	for _, p := range []providerKind{providerNone, providerGollm} {
		if (config{provider: p, effort: highestEffort}).ultracode() {
			t.Errorf("ultracode() = true for non-Claude provider %d, want false", p)
		}
	}
}

func TestInteractiveIdleTimeout(t *testing.T) {
	cases := []struct {
		name string
		set  bool
		val  string
		want time.Duration
	}{
		{name: "valid duration", set: true, val: "100ms", want: 100 * time.Millisecond},
		{name: "invalid falls back to 30m", set: true, val: "bogus", want: 30 * time.Minute},
		{name: "empty falls back to 30m", set: true, val: "", want: 30 * time.Minute},
		{name: "unset falls back to 30m", set: false, want: 30 * time.Minute},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.set {
				t.Setenv("INTERACTIVE_IDLE_TIMEOUT", tc.val)
			} else {
				t.Setenv("INTERACTIVE_IDLE_TIMEOUT", "")
			}
			if got := interactiveIdleTimeout(); got != tc.want {
				t.Errorf("interactiveIdleTimeout() = %v, want %v", got, tc.want)
			}
		})
	}
}

// fakeInput is an in-memory stand-in for the Bandolier input endpoint: each GET
// pops the next queued message; an empty queue answers 204 (no content).
type fakeInput struct {
	frames []string
	i      int32
}

func (f *fakeInput) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	idx := atomic.AddInt32(&f.i, 1) - 1
	if int(idx) >= len(f.frames) {
		w.WriteHeader(http.StatusNoContent)
		return
	}
	_ = json.NewEncoder(w).Encode(map[string]string{"content": f.frames[int(idx)]})
}

func TestAwaitInputSentinel(t *testing.T) {
	srv := httptest.NewServer(&fakeInput{frames: []string{endSessionSentinel}})
	defer srv.Close()

	content, ended := awaitInput(context.Background(), config{inputURL: srv.URL}, time.Minute)
	if !ended {
		t.Errorf("ended = false, want true on sentinel")
	}
	if content != "" {
		t.Errorf("content = %q, want empty", content)
	}
}

func TestAwaitInputContent(t *testing.T) {
	srv := httptest.NewServer(&fakeInput{frames: []string{"hello there"}})
	defer srv.Close()

	content, ended := awaitInput(context.Background(), config{inputURL: srv.URL}, time.Minute)
	if ended {
		t.Errorf("ended = true, want false on content")
	}
	if content != "hello there" {
		t.Errorf("content = %q, want %q", content, "hello there")
	}
}

func TestAwaitInputIdleTimeout(t *testing.T) {
	// A perpetual 204 (never any input) must end the session via the idle deadline.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	}))
	defer srv.Close()

	start := time.Now()
	content, ended := awaitInput(context.Background(), config{inputURL: srv.URL}, 50*time.Millisecond)
	if !ended {
		t.Errorf("ended = false, want true on idle timeout")
	}
	if content != "" {
		t.Errorf("content = %q, want empty", content)
	}
	if time.Since(start) > 30*time.Second {
		t.Errorf("awaitInput took too long to hit idle deadline")
	}
}

func TestAwaitInputContextCancel(t *testing.T) {
	// A perpetual 204 with a cancelled context must exit via the ctx path.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	}))
	defer srv.Close()

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	content, ended := awaitInput(ctx, config{inputURL: srv.URL}, time.Minute)
	if !ended {
		t.Errorf("ended = false, want true on ctx cancel")
	}
	if content != "" {
		t.Errorf("content = %q, want empty", content)
	}
}
